version: "3.9"

services:
  lb:
    build: ./lb
    image: lb
    container_name: lb
    ports:
      - 0.0.0.0:5000:5000
<<<<<<< HEAD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net1:

  # server:
  #   depends_on:
  #     - lb
    # build: ./server
    # image: server
    # container_name: server
    # ports:
    #   - 5000:5000
    # networks:
    #   net1:

networks:
  net1:
=======
    environment:
      - NUM_SERV=3
      - NUM_SLOTS=512
      - NUM_VIRT_SERV=9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

  server:
    # depends_on:
    #   - lb
    build: ./server
    image: server
    # container_name: server
    # ports:
      # - 5000:5000
    # networks:
      # net1:

networks:
  default:
>>>>>>> d0baf8e1f9b3f8c7be44e9844733f395d537336c
    name: net1