version: "3.9"

services:
  lb:
    build: ./lb
    image: lb
    container_name: lb
    ports:
      - 0.0.0.0:5000:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net1:

  # server:
  #   depends_on:
  #     - lb
    # build: ./server
    # image: server
    # container_name: server
    # ports:
    #   - 5000:5000
    # networks:
    #   net1:

networks:
  net1:
    name: net1