build: ./scripts/build.sh
	bash ./scripts/build.sh

run: ./scripts/run.sh
	bash ./scripts/run.sh

monitor: ./scripts/monitor.sh
	bash ./scripts/monitor.sh

kill: ./scripts/kill.sh
	bash ./scripts/kill.sh

clean: ./scripts/clean.sh
	bash ./scripts/clean.sh

test: ./scripts/test.sh
	bash ./scripts/test.sh